"use client";

import Link from "next/link";

const CODE_SNIPPET = `# Generated by QA Deck ✓
def test_login_valid_credentials(driver):
    page = LoginPage(driver)
    page.enter_email("user@example.com")
    page.enter_password("secret123")
    page.click_login()
    assert page.is_dashboard_visible()

def test_login_invalid_password(driver):
    page = LoginPage(driver)
    page.enter_email("user@example.com")
    page.enter_password("wrongpass")
    page.click_login()
    assert page.get_error_message() == \\
        "Epic sadface: Username and password do not match"`;

export default function Hero() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-grid pt-16">
      {/* Radial glow */}
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
        <div className="w-[700px] h-[700px] rounded-full bg-green/5 blur-[120px]" />
      </div>

      <div className="relative max-w-6xl mx-auto px-6 py-24 grid lg:grid-cols-2 gap-16 items-center">
        {/* Left — copy */}
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-green/30 bg-green/10 text-green text-xs font-medium mb-8">
            <span className="w-1.5 h-1.5 rounded-full bg-green animate-pulse" />
            AI-powered · Chrome Extension · Open Source
          </div>

          <h1 className="text-5xl lg:text-6xl font-bold leading-[1.1] tracking-tight mb-6">
            QA Automation
            <br />
            <span className="gradient-text">for Modern Teams</span>
          </h1>

          <p className="text-lg text-white/60 leading-relaxed mb-10 max-w-lg">
            Point QA Deck at any webpage and get production-ready test cases and
            Selenium/Playwright scripts in seconds. No more manual boilerplate.
          </p>

          <div className="flex flex-wrap gap-3">
            <a
              href="https://chromewebstore.google.com/detail/qa-deck/gbccfimmhbdebhiihkgmcdajnbakojed"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-green text-white font-semibold px-6 py-3 rounded-xl hover:bg-green-dark transition-all hover:scale-[1.02] active:scale-[0.98]"
            >
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <circle cx="8" cy="8" r="3" fill="white" />
                <path d="M8 5a3 3 0 100 6A3 3 0 008 5z" fill="white" opacity=".3"/>
                <path d="M5.3 5H1.5M10.7 5H14.5M8 13.5V10" stroke="white" strokeWidth="1.3" strokeLinecap="round"/>
              </svg>
              Install Extension
            </a>
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 bg-white/8 text-white font-semibold px-6 py-3 rounded-xl border border-white/10 hover:bg-white/12 transition-all hover:scale-[1.02] active:scale-[0.98]"
            >
              Sign Up Free
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M3 7h8M8 4l3 3-3 3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </Link>
          </div>

          {/* Social proof */}
          <p className="mt-8 text-xs text-white/30">
            Works with Selenium Python · Selenium Java · Playwright Python · Playwright TypeScript
          </p>
        </div>

        {/* Right — code preview */}
        <div className="relative">
          <div className="rounded-2xl border border-white/8 bg-bg-card overflow-hidden shadow-2xl glow-green">
            {/* Window chrome */}
            <div className="flex items-center gap-1.5 px-4 py-3 border-b border-white/6">
              <span className="w-3 h-3 rounded-full bg-white/15" />
              <span className="w-3 h-3 rounded-full bg-white/15" />
              <span className="w-3 h-3 rounded-full bg-white/15" />
              <span className="ml-3 text-xs text-white/30 font-mono">test_login.py</span>
              <span className="ml-auto flex items-center gap-1 text-xs text-green font-medium">
                <span className="w-1.5 h-1.5 rounded-full bg-green" />
                Generated
              </span>
            </div>
            {/* Code */}
            <pre className="code-block text-white/80 p-5 overflow-x-auto leading-relaxed text-[11.5px]">
              {CODE_SNIPPET.split("\n").map((line, i) => {
                let color = "text-white/70";
                if (line.startsWith("#")) color = "text-white/30";
                else if (line.includes("def ")) color = "text-blue-400";
                else if (line.includes("assert")) color = "text-yellow-400";
                else if (line.includes('"""') || line.match(/"[^"]*"/)) color = "text-orange-300";
                else if (line.includes("page.") || line.includes("driver")) color = "text-green";
                return (
                  <div key={i} className={color}>
                    {line || " "}
                  </div>
                );
              })}
            </pre>
          </div>

          {/* Floating badge */}
          <div className="absolute -top-4 -right-4 bg-green text-white text-xs font-bold px-3 py-1.5 rounded-full shadow-lg">
            ✓ 12 tests generated
          </div>
        </div>
      </div>
    </section>
  );
}
